export const customersData = () => {
    const data = [
        {
            customerID: 1001,
            customer: "Nirav Joshi",
            CustomerEmail: "nirav@gmail.com",
            imgUrl: avatar2,
            deposit: "NGN 34,600",
            date: "Jan 6, 2022 09:21",
            voucherNo: "00437E",
            status: "Successful",
            selected: false,
            customerNumber: "+234 803 0000",
        },
        {
            CustomerID: 1002,
            customer: "Sunil Joshi",
            deposit: "NGN 34,600",
            date: "Jan 6, 2022 09:21",
            voucherNo: "00437E",
            status: "Successful",
            CustomerEmail: "sunil@gmail.com",
            Status: "Active",
            imgUrl: avatar3,
            customerNumber: "+234 803 0000",
            selected: false,
        },
        {
            CustomerID: 1003,
            customer: "Andrew McDownland",
            deposit: "NGN 34,600",
            date: "Jan 6, 2022 09:21",
            voucherNo: "00437E",
            status: "Failed",
            CustomerEmail: "andrew@gmail.com",
            imgUrl: avatar4,
            customerNumber: "+234 803 0000",
        },
        {
            CustomerID: 1004,
            customer: "Christopher Jamil",
            deposit: "NGN 34,600",
            date: "Jan 6, 2022 09:21",
            voucherNo: "00437E",
            status: "Successful",
            CustomerEmail: "jamil@gmail.com",
            imgUrl: avatar,
            customerNumber: "+234 803 0000",
        },
        {
            CustomerID: 1005,
            customer: "Andrew McDownland",
            deposit: "NGN 34,600",
            date: "Jan 6, 2022 09:21",
            voucherNo: "00437E",
            status: "Successful",
            CustomerName: "Michael",
            customerEmail: "michael@gmail.com",
            imgUrl: avatar2,
            customerNumber: "+234 803 0000",
        },
        {
            CustomerID: 1005,
            customer: "Andrew McDownland",
            deposit: "NGN 34,600",
            date: "Jan 6, 2022 09:21",
            voucherNo: "00437E",
            status: "Successful",
            CustomerName: "Michael",
            customerEmail: "michael@gmail.com",
            imgUrl: avatar2,
            customerNumber: "+234 803 0000",
        },
    ];
    return [data];
};
